import type { PeerData } from '@/components/routing'

export const mockPeers: PeerData[] = [
  // Operator: ALPHA_TEAM
  {
    id: 'peer-001',
    identifier: 'NODE_ALPHA_PRIMARY',
    ip: '10.0.0.1/32',
    publicKey: 'xTIBA5rboUvnH4htodjb60Y7YAf8...PQo=',
    role: 'admin',
    device: 'SERVER',
    status: 'online',
    rxTraffic: 78,
    txTraffic: 45,
    lastSeen: '2s ago',
    operatorId: 'ALPHA_TEAM',
  },
  {
    id: 'peer-002',
    identifier: 'NODE_ALPHA_BACKUP',
    ip: '10.0.0.2/32',
    publicKey: 'kYhT3rYp9vqZj8K2nLmPwxRtFgHj...Abc=',
    role: 'admin',
    device: 'SERVER',
    status: 'online',
    rxTraffic: 32,
    txTraffic: 28,
    lastSeen: '1m ago',
    operatorId: 'ALPHA_TEAM',
  },
  // Operator: BETA_CORP
  {
    id: 'peer-003',
    identifier: 'WORKSTATION_BETA_01',
    ip: '10.0.1.10/32',
    publicKey: 'pLmNkOjHgFdSaQwErTyUiOpAsD...Xyz=',
    role: 'employee',
    device: 'DESKTOP',
    status: 'online',
    rxTraffic: 65,
    txTraffic: 72,
    lastSeen: '5s ago',
    operatorId: 'BETA_CORP',
  },
  {
    id: 'peer-004',
    identifier: 'WORKSTATION_BETA_02',
    ip: '10.0.1.11/32',
    publicKey: 'qWeRtYuIoPaAdFgHjKlZxCvBn...Mno=',
    role: 'employee',
    device: 'LAPTOP',
    status: 'warning',
    rxTraffic: 23,
    txTraffic: 18,
    lastSeen: '3m ago',
    operatorId: 'BETA_CORP',
  },
  {
    id: 'peer-005',
    identifier: 'MOBILE_BETA_FIELD',
    ip: '10.0.1.20/32',
    publicKey: 'zXcVbNmAsQwErTyUiOpLkJhGf...Pqr=',
    role: 'employee',
    device: 'MOBILE',
    status: 'idle',
    rxTraffic: 5,
    txTraffic: 3,
    lastSeen: '2h ago',
    operatorId: 'BETA_CORP',
  },
  // Operator: GUEST_ACCESS
  {
    id: 'peer-006',
    identifier: 'GUEST_VISITOR_01',
    ip: '10.0.2.100/32',
    publicKey: 'vBnMkLpOiUyTrEwQaSdFgHjKl...Stu=',
    role: 'guest',
    device: 'LAPTOP',
    status: 'online',
    rxTraffic: 12,
    txTraffic: 8,
    lastSeen: '30s ago',
    operatorId: 'GUEST_ACCESS',
  },
  {
    id: 'peer-007',
    identifier: 'GUEST_CONTRACTOR_A',
    ip: '10.0.2.101/32',
    publicKey: 'nMbVcXzAsQwErTyUiOpLkJhGf...Vwx=',
    role: 'guest',
    device: 'TABLET',
    status: 'offline',
    rxTraffic: 0,
    txTraffic: 0,
    lastSeen: '1d ago',
    operatorId: 'GUEST_ACCESS',
  },
]
